site_name: Ythamos

nav:
  - Home: 'index.md'
  - 'Book Releases':
    - 'Legends of Kora': 'books/legends-of-kora/toc.md'
  - Wiki: 
    - 'The Ythamos': 'wiki/index.md'
    - 'Magic in the Ythamos': 'wiki/magic.md'

theme:
  name: gitbook
